name: data_collection
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.0
  flutter:
    sdk: flutter
  autocomplete_textfield: ^1.7.3
  camera: ^0.8.0
  image_picker: ^0.7.3
  
  provider: ^4.3.3
  awesome_dialog: ^1.3.1
  cupertino_icons: ^1.0.0
  geolocator: ^6.1.14


dev_dependencies:

flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  